# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='价格')),
                ('desc', models.CharField(db_column='desc', max_length=1000, verbose_name='描述')),
                ('picture', models.ImageField(upload_to='static/')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('desc', models.CharField(db_column='desc', default='商品描述', max_length=200, verbose_name='描述')),
                ('flag', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='normal.png', upload_to='static/')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='demo.GoodsType'),
        ),
    ]
